### ISSUE TITLE
Rename the language?

### ISSUE THREAD

**Issue by dbohdan** [FeepingCreature/Cx#3]
Due to the name "Cx" colliding with https://github.com/cx-language/cx/, an active project.

* https://github.com/cx-language/cx/commit/aeee37c8d8f057f9451ef0fc31c7c944865a1dd9 :thinking:

**Comment by rofl0r** [comment]
it seems the delta language was renamed to c* when cx already existed since > 1 year, so imo the other one should be renamed.

**Comment by FeepingCreature** [comment]
Yeah maybe, but this is on me for not jumping on the organization name.

In any case, I've decided to avoid conflict. Cx is now [Neat.](/Neat-Lang/neat)

**Comment by rofl0r** [comment]
what happened to the old neat ?

**Comment by FeepingCreature** [comment]
It's still there. https://github.com/FeepingCreature/fcc But it was never even self-hosting, and it's filled with hacks, so I never felt comfortable advertising it. As a result, it had maybe two users.
